name: Python CI

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup py
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: lint
      run: black .
    - name: flake8
      run: flake8 .