name: Python CI

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: install dependencies
      run: pip install pytest
    - name: run tests
      run: pytest
      working-directory: exercise_2

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: install flake 8
      run: pip install flake8
    - name: check code format
      run: flake8 .
      working-directory: exercise_2