name: exercise5

on:
  push:
    branches:
      - master


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ./.github/actions/greeting
        with:
          who-to-greet: 'Engineers'