name: Python CI

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        run: pytest exercise_2/test_code.py
        run: pytest exercise_2

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: lint
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        run: `black --check .`
        run: `black .`
        run: `flake8 .`